In [9]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 26 16:23:44 2019

@author: Macbook
"""

#-*- coding: utf-8 -*-
from __future__ import print_function
from math import *
import pandas as pd
# from apriori import *  # 导入自行编写的apriori函数
import time  # 导入时间库用来计算用时'
import numpy as np
inputfile = '3.xlsx'  # 输入事务集文件
data = pd.read_excel(inputfile, dtype=object)

# start = time.clock()  # 计时开始
# print(u'\n转换原始数据至0-1矩阵...')
# ct = lambda x: pd.Series(1, index=x)  # 转换0-1矩阵的过渡函数
# b = map(ct, data.as_matrix())  # 用map方式执行
# data = pd.DataFrame(b).fillna(0)  # 实现矩阵转换，空值用0填充
# end = time.clock()  # 计时结束
# print(u'\n转换完毕，用时：%0.2f秒' % (end - start))
# del b  # 删除中间变量b，节省内存

# support = 0.06  # 最小支持度
# confidence = 0.75  # 最小置信度
# ms = '---'  # 连接符，默认'--'，用来区分不同元素，如A--B。需要保证原始表格中不含有该字符

# start = time.clock()  # 计时开始
# print(u'\n开始搜索关联规则...')
# find_rule(data, support, confidence, ms)
# end = time.clock()  # 计时结束
# print(u'\n搜索完成，用时：%0.2f秒' % (end - start))
# data
# data.sort_index()
# for i in range(24061):
#     if(data[i]):
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import  train_test_split
import matplotlib.pyplot as plt
# input Lat_A 纬度A
# input Lng_A 经度A
# input Lat_B 纬度B
# input Lng_B 经度B
# output distance 距离(km)
def calcDistance(Lat_A, Lng_A, Lat_B, Lng_B):
    ra = 6378.140  # 赤道半径 (km)
    rb = 6356.755  # 极半径 (km)
#     print(Lat_A, Lng_A, Lat_B, Lng_B)
    flatten = (ra - rb) / ra  # 地球扁率
    rad_lat_A = radians(Lat_A)
    rad_lng_A = radians(Lng_A)
    rad_lat_B = radians(Lat_B)
    rad_lng_B = radians(Lng_B)
    pA = atan(rb / ra * tan(rad_lat_A))
    pB = atan(rb / ra * tan(rad_lat_B))
    xx = acos(sin(pA) * sin(pB) + cos(pA) * cos(pB) * cos(rad_lng_A - rad_lng_B))
    c1 = (sin(xx) - xx) * (sin(pA) + sin(pB)) ** 2 / cos(xx / 2) ** 2
#     print(xx,pA,pB)
    c2 = (sin(xx) + xx) * (sin(pA) - sin(pB)) ** 2 / sin(xx / 2) ** 2
    dr = flatten / 8 * (c1 - c2)
    distance = ra * (xx + dr)
    return distance
# data=pd.DataFrame(data)
print(data.values)
jl=np.zeros([461,461])
print(jl.shape)
print(data.iat[1,2])
i=np.arange(461)
FIPS_id=zip(i,data['FIPS_Combined'])
# print(FIPS_id.values)
for i in range(461):
    for j in range(461):
        if data.iat[i,1]!=data.iat[j,1] and data.iat[i,2]!=data.iat[j,2]:
            jl[i][j]=calcDistance(data.iat[i,1],data.iat[i,2],data.iat[j,1],data.iat[j,2])

[[54109 37.634 -81.539]
 [54107 39.231 -81.497]
 [54105 39.028 -81.371]
 ...
 [21005 38.018 -84.983]
 [21003 36.78 -86.184]
 [21001 37.089 -85.285]]
(461, 461)
-81.497

In [11]:
jl
np.savetxt('jl.csv', jl, delimiter = ',')
fid = dict( (name,value) for name,value in FIPS_id)
print(fid)
data

{}

    FIPS_Combined      纬度      经度
0           54109  37.634 -81.539
1           54107  39.231 -81.497
2           54105  39.028 -81.371
3           54103  39.593 -80.666
4           54101  38.496 -80.431
5           54099  38.112 -82.418
6           54097  38.928 -80.226
7           54095   39.45  -80.87
8           54093   39.11 -79.563
9           54091   39.32 -80.049
10          54089  37.564 -80.877
11          54087  38.721 -81.314
12          54085  39.168 -81.069
13          54083  38.892 -79.814
14          54081    37.7 -81.224
15          54079  38.537  -81.88
16          54077  39.496 -79.688
17          54075  38.271  -79.99
18          54073  39.369 -81.189
19          54071  38.688 -79.353
20          54069  40.101 -80.629
21          54067  38.282 -80.834
22          54065  39.524 -78.245
23          54063  37.586 -80.539
24          54061   39.64 -80.093
25          54059  37.654 -82.108
26          54057  39.347 -78.964
27          54055  37.435 -81.105
28          54053  38.831 -81.997
29          54051  39.875 -80.694
..            ...     ...     ...
431         21059  37.677 -87.113
432         21057  36.777 -85.408
433         21055  37.352 -88.079
434         21053   36.73 -85.135
435         21051  37.179 -83.737
436         21049   37.98 -84.157
437         21047   36.88 -87.496
438         21045  37.318 -84.935
439         21043  38.328 -83.056
440         21041  38.645 -85.133
441         21039  36.845 -88.996
442         21037  38.931 -84.369
443         21035  36.624  -88.26
444         21033  37.151 -87.888
445         21031  37.182 -86.671
446         21029  37.951 -85.683
447         21027  37.782 -86.414
448         21025  37.539 -83.264
449         21023  38.686  -84.07
450         21021  37.624 -84.845
451         21019  38.373 -82.694
452         21017  38.224 -84.205
453         21015  38.988 -84.747
454         21013  36.705 -83.708
455         21011  38.137 -83.721
456         21009  36.944 -85.957
457         21007  37.074 -88.999
458         21005  38.018 -84.983
459         21003   36.78 -86.184
460         21001  37.089 -85.285

[461 rows x 3 columns]

In [60]:
print(jl)

[[  0.           0.           0.         ...   0.           0.
    0.        ]
 [  0.           0.          25.03197614 ... 332.06117365 493.30605757
  408.27970781]
 [  0.          25.03197614   0.         ... 334.31298378 491.24975212
  405.29774366]
 ...
 [  0.           0.           0.         ...   0.           0.
    0.        ]
 [  0.           0.           0.         ...   0.           0.
    0.        ]
 [  0.           0.           0.         ...   0.           0.
    0.        ]]